name: KOMTUS
favicon: null
layout_spectrum: 0.24903538031503558
typography_spectrum: 0.5123827729839832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6955807814374566
  lightness: 0.32818087097257376
  saturation: 0.8585440393071622
  rhythmicContrast: 0.11556224804371595
purpose: []
