name: KOMTUS
favicon: null
layout_spectrum: 0.25382
typography_spectrum: 0.4966
title: Navigating Industrial Internet of Things
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#19bcff'
    - '#595959'
    - '#b6b6b7'
  brandStrength: 0.6955807814374566
  lightness: 0.32818087097257376
  saturation: 0.8585440393071622
  rhythmicContrast: 0.11556224804371595
purpose: []
